### ISSUE TITLE
Specific file is not watched

### ISSUE THREAD

**Issue by fredrikekre** [tlienart/LiveServer.jl#125]
Hi, I tried `LiveServe.servedocs` with Literate and it seems to work *except* the file [`docs/src/outputformats.md`](https://github.com/fredrikekre/Literate.jl/blob/master/docs/src/outputformats.md) is not watched for some reason. Changes to all other files trigger a rebuild.

I ran this from the Literate.jl root:
```
julia --project=docs -e 'using LiveServer; LiveServer.servedocs(; skip_dir="docs/src/generated")
```

The only unique thing with this file (compared to the other) is that there is also a file [`docs/src/outputformats.jl`](https://github.com/fredrikekre/Literate.jl/blob/master/docs/src/outputformats.jl), but don't quite know why that would matter.

**Comment by fredrikekre** [comment]
Yep, seems like that is the problem. Changing it to `outputformats2.md` works.

**Comment by fredrikekre** [comment]
https://github.com/tlienart/LiveServer.jl/blob/e0301cbe2334c7ee9bc230f1468d53bf4e61b5e2/src/utils.jl#L75-L87

Why is that there?

**Comment by tlienart** [comment]
Hello Fredrik,

The procedure expected with literate is outlined here: https://tlienart.github.io/LiveServer.jl/dev/man/ls+lit/#Modifying-the-make-file meaning that if there's a file `literate_src.jl` you'll get a `literate_src.md` in the same folder which shouldn't be watched otherwise there's an infinite triggering (make.jl file executed -> generates .md file -> triggers -> make.jl file executed)

I think here the issue is rather that you're not using Literate and so this code should not apply to your case. I think the correct thing to do would be to have default `literate=nothing`) (meaning that we don't expect to use Literate), and then if the user wants either `literate=""` or `literate="path/to/literate_files/` .

**Comment by fredrikekre** [comment]
> The procedure expected with literate is outlined here: https://tlienart.github.io/LiveServer.jl/dev/man/ls+lit/#Modifying-the-make-file meaning that if there's a file literate_src.jl you'll get a literate_src.md in the same folder which shouldn't be watched otherwise there's an infinite triggering (make.jl file executed -> generates .md file -> triggers -> make.jl file executed)

Yes, but I thought it was opt-in? I am not specifying that I am using Literate here, but perhaps I misunderstood the meaning of the `literate` keyword argument.

**Comment by tlienart** [comment]
yes this is the problem; the default is `literate=""` which still assumes that you _might_ be using literate but in the current directory. 

What I'm suggesting is to have default be `literate=nothing` and then have the user specify explicitly either `literate=""` or `literate="path/to"` in which case the behaviour would be triggered. I'll add that now
